/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/Chart/barChart.vue')['default']
    BaseMap: typeof import('./src/components/BaseMap/index.vue')['default']
    CarouselImage: typeof import('./src/components/carouselImage/index.vue')['default']
    CarouselModule: typeof import('./src/components/carouselImage/carouselModule.vue')['default']
    CommonModuleHeader: typeof import('./src/components/CommonModuleHeader/index.vue')['default']
    CommonSubHeader: typeof import('./src/components/CommonSubHeader/index.vue')['default']
    IndexLeft: typeof import('./src/components/Toolbar/indexLeft.vue')['default']
    LayerSwitch: typeof import('./src/components/Toolbar/components/LayerSwitch.vue')['default']
    LightRingChart: typeof import('./src/components/Chart/lightRingChart.vue')['default']
    MapContainer: typeof import('./src/components/MapContainer/index.vue')['default']
    MapRecovery: typeof import('./src/components/Toolbar/components/MapRecovery.vue')['default']
    MapSearch: typeof import('./src/components/Toolbar/components/MapSearch.vue')['default']
    ModuleScreenHeader: typeof import('./src/components/ModuleScreenHeader/index.vue')['default']
    PieChart: typeof import('./src/components/Chart/pieChart.vue')['default']
    PieChat: typeof import('./src/components/Chart/pieChat.vue')['default']
    Ranking: typeof import('./src/components/Chart/ranking.vue')['default']
    RingChart3D: typeof import('./src/components/Chart/ringChart3D.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemInfo: typeof import('./src/components/SystemInfo/index.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar/index.vue')['default']
    WaterQualityRanking: typeof import('./src/components/Chart/waterQualityRanking.vue')['default']
  }
}
